name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make dep
    
    - name: Build
      run: make build
    
    - name: Test
      run: make test

    - name: Run coverage
      run: make cov
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
